name: "Run stress tests"

on:
  workflow_dispatch:

jobs:
  run-stress-tests:
    name: Stress tests
    uses: "./.github/workflows/run-stress-tests-reusable.yaml"
    secrets: inherit
    with:
      image-tag: PR-${{ github.event.number }}
      module-tag: v0.0.0-PR-${{ github.event.number }}
      image-repo: europe-docker.pkg.dev/kyma-project/dev/btp-manager
      module-repo: europe-docker.pkg.dev/kyma-project/dev/unsigned/component-descriptors/kyma.project.io/module/btp-operator
